apiVersion: apps/v1
metadata:
  labels:
    project: ${project.artifactId}
    version: ${project.version}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: ${project.artifactId}
        version: ${project.version}    
    spec:                 
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Dspring.profiles.active=sharding-databases
        - name: JAVA_ENABLE_DEBUG
          value: "true"
        imagePullPolicy: Always   
      imagePullSecrets:
      - name: secret-aliyuncs
           
                    