metadata:
  labels:
    project: ${project.artifactId}
    version: ${project.version}
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    project: ${project.artifactId}
    
